### PR TITLE
catalogue first update

### PR DESCRIPTION
**Pull request by sakil98**
hai saya sakil

### CODE REVIEW

**Comment by IzzatHalabi** [comment]
Very interesting. good job.

**Comment by IzzatHalabi** [comment]
Seems good to me!

**Comment by sakil98** [comment]
Thank you kind sir

**Comment by sakil98** [comment]
Changelog:
Added 6 new views
Added navbar for easy navigation
Added 4 seeders (updated DatabaseSeeder to run all seeders)
Added 6 controllers
Added 6 models and migration

Not implemented yet:
Receipt page
Receipt list
Logic to retrieve data for receipt unfinished aq jem otak mengantuk nak tidur mana

**Pull request merged**
